In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r'movie_metadata.csv')

In [26]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [4]:
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [5]:
df[['genres', 'movie_title', 'movie_imdb_link','imdb_score']]

,genres,movie_title,movie_imdb_link,imdb_score
0,Action|Adventure|Fantasy|Sci-Fi,Avatar,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,7.9
1,Action|Adventure|Fantasy,Pirates of the Caribbean: At World's End,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,7.1
2,Action|Adventure|Thriller,Spectre,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,6.8
3,Action|Thriller,The Dark Knight Rises,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,8.5
4,Documentary,Star Wars: Episode VII - The Force AwakensÂ ...,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,7.1
...,...,...,...,...
5038,Comedy|Drama,Signed Sealed Delivered,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,7.7
5039,Crime|Drama|Mystery|Thriller,The Following,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,7.5
5040,Drama|Horror|Thriller,A Plague So Pleasant,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,6.3
5041,Comedy|Drama|Romance,Shanghai Calling,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,6.3
5042,Documentary,My Date with Drew,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,6.6

In [6]:
selected_data=df[['genres', 'movie_title', 'movie_imdb_link','imdb_score']]

In [7]:
selected_data

,genres,movie_title,movie_imdb_link,imdb_score
0,Action|Adventure|Fantasy|Sci-Fi,Avatar,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,7.9
1,Action|Adventure|Fantasy,Pirates of the Caribbean: At World's End,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,7.1
2,Action|Adventure|Thriller,Spectre,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,6.8
3,Action|Thriller,The Dark Knight Rises,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,8.5
4,Documentary,Star Wars: Episode VII - The Force AwakensÂ ...,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,7.1
...,...,...,...,...
5038,Comedy|Drama,Signed Sealed Delivered,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,7.7
5039,Crime|Drama|Mystery|Thriller,The Following,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,7.5
5040,Drama|Horror|Thriller,A Plague So Pleasant,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,6.3
5041,Comedy|Drama|Romance,Shanghai Calling,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,6.3
5042,Documentary,My Date with Drew,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,6.6

In [8]:
genres_list=[selected_data .loc[i]['genres'].split('|') for i in selected_data .index]

In [9]:
genreslist = sorted(list(set([item for sublist in genres_list for item in sublist])))

In [10]:
genreslist

['Action',
 'Adventure',
 'Animation',
 'Biography',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Family',
 'Fantasy',
 'Film-Noir',
 'Game-Show',
 'History',
 'Horror',
 'Music',
 'Musical',
 'Mystery',
 'News',
 'Reality-TV',
 'Romance',
 'Sci-Fi',
 'Short',
 'Sport',
 'Thriller',
 'War',
 'Western']

In [11]:
genreslist[0]

'Action'

In [12]:
print(genreslist)

['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Film-Noir', 'Game-Show', 'History', 'Horror', 'Music', 'Musical', 'Mystery', 'News', 'Reality-TV', 'Romance', 'Sci-Fi', 'Short', 'Sport', 'Thriller', 'War', 'Western']

In [13]:
print(len(genreslist))

26

In [14]:
title=[]
for i in selected_data.index:
    title.append(selected_data.loc[i]['movie_title'].strip(),i,selected_data.loc[i]['movie_imdb_link'])

TypeError: list.append() takes exactly one argument (3 given)

In [15]:
for i in selected_data.index:
    title.append((selected_data.loc[i]['movie_title'].strip(),i,selected_data.loc[i]['movie_imdb_link'].strip())

SyntaxError: unexpected EOF while parsing (1571517975.py, line 2)

In [16]:
title=[]

In [17]:
for i in selected_data.index:
    title.append((selected_data.loc[i]['movie_title'].strip(),i,selected_data.loc[i]['movie_imdb_link'].strip()))

In [19]:
import json

In [18]:
movie_info=[]
for i in selected_data.index:
    data=[1 if genre in selected_data.loc[i]['genres'].split('|') else 0 for genre in genreslist]
    data.append(selected_data.loc[i]['imdb_score'])
    movie_info.append(data)

In [20]:
data1 = r'title.json'

In [23]:
with open(data1,'w+',encoding='utf-8') as final:
    json.dump(title,final)

In [24]:
data2=r'data.json'

In [25]:
with open(data2,'w+',encoding='utf-8') as final:
    json.dump(movie_info,final)

In [4]:
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [5]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [6]:
new_data=df[['movie_title','genres','director_name','movie_imdb_link','imdb_score']]

In [8]:
new_data.head()

,movie_title,genres,director_name,movie_imdb_link,imdb_score
0,Avatar,Action|Adventure|Fantasy|Sci-Fi,James Cameron,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,7.9
1,Pirates of the Caribbean: At World's End,Action|Adventure|Fantasy,Gore Verbinski,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,7.1
2,Spectre,Action|Adventure|Thriller,Sam Mendes,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,6.8
3,The Dark Knight Rises,Action|Thriller,Christopher Nolan,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,8.5
4,Star Wars: Episode VII - The Force AwakensÂ ...,Documentary,Doug Walker,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,7.1

In [9]:
import pickle

In [10]:
pickle.dump(new_data.to_dict(),open('info.pkl','wb'))